### ISSUE TITLE
Changing ports causes exceptions

### ISSUE THREAD

**Issue by sandervandevelde** [iot-edge-foundation/iot-edge-serial#1]
when I change an excisiting port (eg /dev/ttyACM0) to an unexcisting port (eg ttyACM1) using the desired properties, I get an exception. If i change it back, I get a more exciting exception: een instance of an object not found.

**Comment by JeeWeetje** [comment]
Any update on testing on this one, @sandervandevelde ?

**Comment by JeeWeetje** [comment]
Oops, wrong button pressed. ;-)

**Comment by sandervandevelde** [comment]
The var 'serialPort' in 'serialPort.Read' is null when changing to an unsupported port.

This can be fixed with:

```
            while (_run && bytesRead < 1024)
            {
                if (serialPort == null)
                {
                    Log.Verbose("svdv in while -> serial port is null");
                    Thread.Sleep(50);            
                    return temp.ToArray();
                }

                var i = serialPort.Read(buf, 0, 1);
```

But this look like an indication of a failing: 

```
  _run = false;
  await Task.WhenAll(_taskList); // wait until all tasks are completed
```

The while loop keeps running when it should have been stopped and the task should have been removed...

**Comment by sandervandevelde** [comment]
Issue fixed for Linux. Task running on 'old' serial port is now proper aborted.
In Windows, we get an 'operation timed out' when changing to other serial port

**Comment by sandervandevelde** [comment]
Fixed port changing in windows.
