### ISSUE TITLE
[B] jeeweetje/iot-edge-serial:0.0.46-windows-amd64 - Module fails to start due to wrong device assignment 

### ISSUE THREAD

**Issue by JeeWeetje** [iot-edge-foundation/iot-edge-serial#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Bare minimum steps
- Install IoT Edge on a Windows based machine
- Attach a serial device which provides data on the serial port (most likely an serial to USB on)
- Make sure you have the drivers and are able to read the data on the port in PS
- Close port in PS again
- Add module jeeweetje/iot-edge-serial:0.0.46-windows-amd64 to deployment manifest
- properly set the com port configuration as descriped in the repo readme
- Deploy new manifest
- check ```iotedge logs edgeAgent --tail 100 -f``` to follow the installation
- Note the exception on the device access

### Any log messages given by the failure
> Unable to provide yet, due to finding the issue during a HOL set-up which got wiped too soon to save the logs

### Expected/desired behavior
> Reading data from the COM port and transporting it via routes to other modules or $upstream

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). mac OS (Yosemite? El Capitan? Sierra?)
- Windows IoT Enterprise 1809

### Versions
> jeeweetje/iot-edge-serial:0.0.46-windows-amd64

#### other

> ---------------------------------------------------------------
> Thanks a lot! We'll get in touch soon.

**Comment by SpaBruis** [comment]
Are there any updates on this bug?

**Comment by JeeWeetje** [comment]
@SpaBruis we updated the code and bumped version of the images to 0.1.3 since we moved from .net core 2.1 to .net core 3.1, so native support for cross platform serial port is available now. We have tested the image with a Windows 10 (>= build 1809) to read data from a serial port which worked.

Please check the [code](https://github.com/iot-edge-foundation/iot-edge-serial) or the [images](https://hub.docker.com/r/iotedgefoundation/iot-edge-serial). If you find any issues, file them or contribute with a pull request to fix them yourself.
