### ISSUE TITLE
Set Module in Azure IoT Hub Instructions

### ISSUE THREAD

**Issue by donniekerr** [iot-edge-foundation/iot-edge-serial#8]
I'm having trouble understanding the instructions on how to use this module in Azure IoT Hub.  

I just need to use your image as is and not build my own.  But, I do need to change it to listen on any port on a Windows. I do not wish to modify the code since I'm not a Csharp developer. Do I still need to setup a project in VSCode? 

How do I fill out the set module forms to load your image? How do I change the deployment settings to Windows ports? Do I need my own container registry in ACR?  If so, how do I get your image into it?  If not, what do I put in for credentials? 

I see how to create the image in Docker Images and I see how to change to Windows in the config/deployment file and I do get deployment success.  But, the module does not get installed on the Edge Device.  I just can't get it setup correctly in Set Module.

I would appreciate your help very much as I must get the iGrow 1800 controller connecting to Azure IoT for our hemp farm operations. Thank you!

**Comment by sandervandevelde** [comment]
Hello @donniekerr,  

This docker container for serial port communication is especially build for [Azure IoT Edge](https://azure.microsoft.com/en-us/services/iot-edge/).

It's made available for free and with a MIT license.

You can either use the ready-to-use container made available on our [docker hub](https://hub.docker.com/r/iotedgefoundation/iot-edge-serial) or you can choose to build and push your own version to the container repository to own yourself (eg. Azure Container Registry). For that, you need Visual Studio or Visual Studio Code and Docker CE.

The module reads data from a serial port and splits the stream in messages using the delimiter. 

In the SetModules wizard in the Azure portal, fill in a name of your choice, the uri of your container of choice, add the container create options either for Windows or Linux and provide the desired properties of your serial port settings.

It seems you are using Windows, in that case you have not to worry about elevated rights for the serial port like you have to do in Linux.

I recommend you to learn the basic concepts of Azure IoT Edge in general. There is [documentation](https://azure.microsoft.com/en-us/services/iot-edge/) available which shows how to setup an IoT Edge runtime and moby container runtime. 

Does this help to get your device up and running?

**Comment by JeeWeetje** [comment]
@donniekerr do you know which port your device is connected to on Windows? (e.g. COM1 or COM2)?

If you know the serial port properties like baud rate, data bits, stop bits, parity and such, I can construct a sample deployment manifest for you.

It an iGrow 1800 (the greenhouse control unit?) you want to connect, I understood from @sandervandevelde?

Provide some technical details on the port it is connecting to on windows (device manager might be helpful to determine which port it is using) and we are glad to get you going.

**Comment by JeeWeetje** [comment]
Closed due to inactivity.
