### ISSUE TITLE
The container operating system does not match the host operating system.

### ISSUE THREAD

**Issue by reneprins4** [iot-edge-foundation/iot-edge-serial#9]
Hi,

First of all thank you for the module you have developed.
I'm trying in my Azure IoT C# project to add the serial module, I did that by grabbing the docker image (0.1.5-windows-amd64) as external module and adding it.

My machine is running on Windows 10 and I also have Windows docker containers set up. I have found on various forums that I have to install windows/servercore or windows/nanocore as a container, I did that and unfortunately that doesn't work.

Do I have to run a particular docker container or do some other setting?

Error:

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error : Creating SerialReaderModule ... 
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error : Creating SerialReaderModule ... error
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error : ERROR: for SerialReaderModule  Cannot start service SerialReaderModule: hcsshim::CreateComputeSystem e8e4d08551d083dc780e1745fedd60bcfff7cb4ec170afe944be760e81681eb9: The container operating system does not match the host operating system.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error : Creating EchoModule         ... done
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error : ERROR: for SerialReaderModule  Cannot start service SerialReaderModule: hcsshim::CreateComputeSystem e8e4d08551d083dc780e1745fedd60bcfff7cb4ec170afe944be760e81681eb9: The container operating system does not match the host operating system.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error : Encountered errors while bringing up the project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error : ERROR: Error while executing command: docker-compose -f C:\ProgramData\iotedgehubdev\data\data\docker-compose.yml up -d. Command '['docker-compose', '-f', 'C:\\ProgramData\\iotedgehubdev\\data\\data\\docker-compose.yml', 'up', '-d']' returned non-zero exit status 1.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error :    --- End of inner exception stack trace ---
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error :    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error :    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error :    at Microsoft.VisualStudio.Azure.IoT.Edge.BuildTasks.PrepareEdgeCliTask.<ExecuteCoreAsync>d__22.MoveNext()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error : --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error :    at Microsoft.VisualStudio.Azure.IoT.Edge.BuildTasks.EdgeTaskBase.<ExecuteAsync>d__22.MoveNext()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error : ---> (Inner Exception #0) Microsoft.VisualStudio.Azure.IoT.Edge.Infrastructure.Utilities.CommandLineClientException: Stopping EchoModule ... 

My deployment.template.json:
"portConfigs": {
          "COM7": {
            "device": "COM7",
            "direction": "Read",
            "sleepInterval": 10,
            "baudRate": 1552000,
            "parity": "One",
            "dataBits": 8,
            "stopBits": "One",
            "delimiter": "\r\n",
            "ignoreEmptyLines": true,
            "delimiterAtStart": false,
            "delimiterInOutput": false
          }
        }

And

"SerialReaderModule": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "iotedgefoundation/iot-edge-serial:0.1.5-windows-amd64",
              "createOptions": {
                "HostConfig": {
                  "Isolation": "Process",
                  "Devices": [
                    {
                      "PathOnHost": "class/86E0D1E0-8089-11D0-9CE4-08003E301F73",
                      "PathInContainer": "",
                      "CgroupPermissions": ""
                    }
                  ]
                }
              }
            }
          }

Thanks!

**Comment by JeeWeetje** [comment]
Windows version of this module has been deprecated.
